### ISSUE TITLE
composer support

### ISSUE THREAD

**Issue by ahmedrabii** [emiliemarchand/PrismPollBundle#1]
i can't finde out how to install this bundel with composer , can any one tell me plees !!

**Comment by ashokchitroda** [comment]
I also not find... Can any body to tell??

**Comment by emiliemarchand** [comment]
It currently does not have support for composer. It's in the TODO list

**Comment by ashokchitroda** [comment]
Yes, last i have tried to download bundle and install manually but not work for me. I click on "add new" link it's called edit event.. last i debugged code but i can't find any action to add new poll..

**Comment by emiliemarchand** [comment]
The bundle is now updated to work with Symfony 2.4.x and a composer.json has been added

**Comment by hgraca** [comment]
This does not install with composer. You need to add it to packagist.

**Comment by emiliemarchand** [comment]
You're right, I totally forgot about it! It should be there now! Thanks :)
